fix IP concatenation bug
microsoft/SDN pull request #538
Opened 2022-11-07 18:47 UTC by vlappenbusch

Some IPs to skip were being concatenated by string value, which could have been caused by initially setting the $ips variable to a single IP with the get-pacamapping call

2022-11-07 18:48 UTC, vlappenbusch commented
@microsoft-github-policy-service agree [company="Microsoft"]

2022-11-07 18:49 UTC, vlappenbusch commented
@microsoft-github-policy-service agree company="Microsoft"

2022-11-09 18:10 UTC, sbgms requested changes

2022-11-09 18:10 UTC, sbgms commented on SDNExpress/scripts/SDNExpressModule.psm1
> +            Write-LogInfo $OperationID "PA IPs is null. Setting to empty array"
It doesnt look like we're setting it. Maybe we should skip the trace ?

2022-11-09 18:10 UTC, sbgms commented on SDNExpress/scripts/SDNExpressModule.psm1
> +        foreach ($res in $logicalsubnet.Properties.IpReservations) {
Add a comment why we're doing it. Someone might need to know this in future.

2022-11-09 18:47 UTC, merged