dump counter values of vfp rules
microsoft/SDN pull request #568
Opened 2023-03-25 00:56 UTC by jayanthaMicrosoft

Adding an additional "/get-rule-counter" command to the VFP data dumped for a VFP-Port.

2023-04-09 12:46 UTC, debj1t requested changes

2023-04-09 12:46 UTC, debj1t commented on Kubernetes/windows/debug/dumpVfpPolicies.ps1
>  	& $vfpCtrlExe /list-rule  /port $portGuid | Out-File $outfile -Encoding ascii -Append
can you replace the /list-rule command with /get-rule-counter instead of appending it?
/get-rule-counter = /list-rule with rule counters

2023-04-10 05:27 UTC, debj1t approved these changes

2023-04-20 09:40 UTC, princepereira approved these changes
lgtm

2023-04-25 17:32 UTC, daschott reviewed
Why /list-rule is removed? Shouldn't we add /get-rule-counter and preserve /list-rule?

2023-04-26 13:50 UTC, merged